# Generated by Django 4.1.2 on 2022-10-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
    ]
