# Generated by Django 4.1.2 on 2022-10-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_question_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="answer1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer3",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer4",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
