# Generated by Django 4.1.2 on 2022-10-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_app.category",
            ),
            preserve_default=False,
        ),
    ]
