# Generated by Django 4.1.2 on 2022-10-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
