# Generated by Django 4.1.2 on 2022-10-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="question",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.question",
            ),
            preserve_default=False,
        ),
    ]
