# Generated by Django 4.1.2 on 2022-10-24 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_remove_question_category_category_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="question",
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.category",
            ),
            preserve_default=False,
        ),
    ]
