# Generated by Django 4.1.2 on 2022-10-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_remove_category_question_question_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
    ]
