# Generated by Django 4.1.2 on 2022-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("U", "Uncategorized"),
                    ("B", "Behavioral"),
                    ("LF", "Language-Frontend"),
                    ("LB", "Language-Backend"),
                    ("FF", "Frameworks-Frontend"),
                    ("FB", "Frameworks-Backend"),
                    ("D", "Data Structures"),
                    ("A", "Algorithms"),
                ],
                default="U",
                max_length=2,
            ),
        ),
    ]
